# Generated by Django 3.2.4 on 2021-06-28 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ('-publish',)},
        ),
        migrations.RenameField(
            model_name='story',
            old_name='footer',
            new_name='des',
        ),
    ]
