# Generated by Django 3.2.4 on 2021-07-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0003_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='repassword',
            field=models.IntegerField(),
        ),
    ]
