# Generated by Django 3.2.4 on 2021-07-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0004_auto_20210707_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
